#include "metrics_table.hpp"
#include "gcloud_client.hpp"
#include "gcloud_secret.hpp"
#include "gcloud_json.hpp"
#include "gcloud_yyjson.hpp"
#include "duckdb/common/exception.hpp"
#include "duckdb/common/string_util.hpp"
#include "duckdb/common/types/timestamp.hpp"
#include "duckdb/function/table_function.hpp"
#include "duckdb/main/extension/extension_loader.hpp"
#include <deque>
#include <set>
using namespace duckdb_yyjson; // NOLINT
namespace duckdb { namespace {
struct DD {void operator()(yyjson_doc*d)const{yyjson_doc_free(d);}};using Doc=std::unique_ptr<yyjson_doc,DD>;constexpr idx_t TIME=0,START=1,NAME=2,UNIT=4,INT=5,DOUBLE=6,SERVICE=7,NAMESPACE=8,INSTANCE=9,RESOURCE=10,ATTRS=14;
struct Point {int64_t time=0,start=0,integer=0;double decimal=0;bool has_start=false,is_integer=false;string metric,unit,resource_type,metric_labels,resource_labels,kind,type;};struct Bind:TableFunctionData{string project,filter,start="-15m",end="now",align,aligner,reducer;vector<string>groups;int64_t page_size=10000,max=0;GcloudClient client;};struct State:GlobalTableFunctionState{vector<column_t>cols;std::deque<Point>points;string token;std::set<string>seen;string start,end;idx_t emitted=0;bool done=false;idx_t MaxThreads()const override{return 1;}};
static string E(const string&s){static constexpr char H[]="0123456789ABCDEF";string r;for(auto x:s){auto c=(unsigned char)x;if((c>='a'&&c<='z')||(c>='A'&&c<='Z')||(c>='0'&&c<='9')||c=='-'||c=='_'||c=='.'||c=='~')r+=char(c);else{r+='%';r+=H[c>>4];r+=H[c&15];}}return r;}static string V(yyjson_val*v){size_t n=0;char*p=yyjson_val_write(v,0,&n);if(!p)return {};string r(p,n);free(p);return r;}static string G(yyjson_val*o,const char*k){auto v=o?yyjson_obj_get(o,k):nullptr;return v&&yyjson_is_str(v)?string(yyjson_get_str(v),yyjson_get_len(v)):string();}
static string Path(const Bind&b,const State&s){string q="filter="+E(b.filter)+"&interval.startTime="+E(s.start)+"&interval.endTime="+E(s.end)+"&pageSize="+std::to_string(b.page_size)+"&view=FULL";if(!b.align.empty())q+="&aggregation.alignmentPeriod="+E(b.align);if(!b.aligner.empty())q+="&aggregation.perSeriesAligner="+E(b.aligner);if(!b.reducer.empty())q+="&aggregation.crossSeriesReducer="+E(b.reducer);for(auto&g:b.groups)q+="&aggregation.groupByFields="+E(g);if(!s.token.empty())q+="&pageToken="+E(s.token);return "/v3/projects/"+E(b.project)+"/timeSeries?"+q;}
static void Fetch(ClientContext&c,const Bind&b,State&s){auto body=b.client.Get(c,Path(b,s),"Cloud Monitoring");Doc d(yyjson_read(body.c_str(),body.size(),0));if(!d)throw IOException("Cloud Monitoring metrics returned invalid JSON");auto root=yyjson_doc_get_root(d.get());auto ts=yyjson_obj_get(root,"timeSeries");if(ts&&!yyjson_is_arr(ts))throw IOException("Cloud Monitoring metrics response has malformed timeSeries");if(ts){size_t i,n;yyjson_val*x;yyjson_arr_foreach(ts,i,n,x){auto metric=yyjson_obj_get(x,"metric"),resource=yyjson_obj_get(x,"resource"),points=yyjson_obj_get(x,"points");auto type=G(metric,"type");if(type.empty()||!points||!yyjson_is_arr(points))throw IOException("Cloud Monitoring metrics response has malformed time series");size_t j,m;yyjson_val*p;yyjson_arr_foreach(points,j,m,p){auto interval=yyjson_obj_get(p,"interval"),value=yyjson_obj_get(p,"value");int64_t end; if(!ParseRfc3339ToNanos(GcloudGetStr(interval,"endTime"),end))throw IOException("Cloud Monitoring metrics response has malformed point endTime for %s",type);Point out;out.time=end;out.metric=type;out.unit=G(x,"unit");out.resource_type=G(resource,"type");out.metric_labels=V(yyjson_obj_get(metric,"labels"));out.resource_labels=V(yyjson_obj_get(resource,"labels"));out.kind=G(x,"metricKind");out.type=G(x,"valueType");auto st=GcloudGetStr(interval,"startTime");if(st){out.has_start=ParseRfc3339ToNanos(st,out.start);if(!out.has_start)throw IOException("Cloud Monitoring metrics response has malformed point startTime for %s",type);}auto iv=yyjson_obj_get(value,"int64Value"),dv=yyjson_obj_get(value,"doubleValue");if(iv&&yyjson_is_str(iv)){char*e=nullptr;out.integer=strtoll(yyjson_get_str(iv),&e,10);if(!e||*e)throw IOException("Cloud Monitoring metrics returned malformed int64Value for %s",type);out.is_integer=true;}else if(dv&&yyjson_is_num(dv)){out.decimal=yyjson_get_real(dv);}else{auto unsupported=value&&yyjson_is_obj(value)?"unsupported":"missing";throw IOException("Cloud Monitoring metrics returned %s value type for %s",unsupported,type);}s.points.push_back(std::move(out));}}}auto next=G(root,"nextPageToken");if(next.empty()||next==s.token||!s.seen.insert(next).second)s.done=true;else s.token=next;}
static string Q(const string&s){string o="\"";for(char c:s){if(c=='\\'||c=='\"')o+='\\';o+=c;}return o+"\"";}static string Resource(const Bind&b,const Point&p){string x="{\"cloud.provider\":\"gcp\",\"gcp.project\":"+Q(b.project);if(!p.resource_type.empty())x+=",\"gcp.resource_type\":"+Q(p.resource_type);if(!p.resource_labels.empty())x+=",\"resource.labels\":"+p.resource_labels;return x+"}";}static string Attr(const Bind&b,const Point&p){string x="{\"metric.labels\":"+(p.metric_labels.empty()?"{}":p.metric_labels)+",\"metricKind\":"+Q(p.kind)+",\"valueType\":"+Q(p.type);if(!b.align.empty())x+=",\"alignmentPeriod\":"+Q(b.align);if(!b.aligner.empty())x+=",\"perSeriesAligner\":"+Q(b.aligner);if(!b.reducer.empty())x+=",\"crossSeriesReducer\":"+Q(b.reducer);return x+"}";}
static string Label(const string&json,const char*k){Doc d(yyjson_read(json.c_str(),json.size(),0));return G(d?yyjson_doc_get_root(d.get()):nullptr,k);}static void Map(const Bind&b,const State&s,const Point&p,DataChunk&o,idx_t row){for(idx_t i=0;i<s.cols.size();i++){o.SetValue(i,row,Value());switch(s.cols[i]){case TIME:o.SetValue(i,row,Value::TIMESTAMPNS(timestamp_ns_t(p.time)));break;case START:if(p.has_start)o.SetValue(i,row,Value::TIMESTAMPNS(timestamp_ns_t(p.start)));break;case NAME:o.SetValue(i,row,Value(p.metric));break;case UNIT:if(!p.unit.empty())o.SetValue(i,row,Value(p.unit));break;case INT:if(p.is_integer)o.SetValue(i,row,Value::BIGINT(p.integer));break;case DOUBLE:if(!p.is_integer)o.SetValue(i,row,Value::DOUBLE(p.decimal));break;case SERVICE:{auto v=Label(p.resource_labels,"service.name");if(v.empty())v=Label(p.metric_labels,"service.name");if(!v.empty())o.SetValue(i,row,Value(v));break;}case NAMESPACE:{auto v=Label(p.resource_labels,"service.namespace");if(v.empty())v=Label(p.metric_labels,"service.namespace");if(!v.empty())o.SetValue(i,row,Value(v));break;}case INSTANCE:{auto v=Label(p.resource_labels,"service.instance.id");if(v.empty())v=Label(p.metric_labels,"service.instance.id");if(!v.empty())o.SetValue(i,row,Value(v));break;}case RESOURCE:o.SetValue(i,row,Value(Resource(b,p)));break;case ATTRS:o.SetValue(i,row,Value(Attr(b,p)));break;default:break;}}}
static unique_ptr<FunctionData>B(ClientContext&c,TableFunctionBindInput&i,vector<LogicalType>&t,vector<string>&n){auto b=make_uniq<Bind>();string secret;for(auto&p:i.named_parameters){if(p.second.IsNull())continue;auto k=StringUtil::Lower(p.first);if(k=="project")b->project=p.second.ToString();else if(k=="filter")b->filter=p.second.ToString();else if(k=="start_time")b->start=p.second.ToString();else if(k=="end_time")b->end=p.second.ToString();else if(k=="alignment_period")b->align=p.second.ToString();else if(k=="per_series_aligner")b->aligner=p.second.ToString();else if(k=="cross_series_reducer")b->reducer=p.second.ToString();else if(k=="group_by_fields"){for(auto&v:ListValue::GetChildren(p.second)){if(!v.IsNull())b->groups.push_back(v.ToString());}}else if(k=="page_size")b->page_size=p.second.GetValue<int64_t>();else if(k=="max_rows")b->max=p.second.GetValue<int64_t>();else if(k=="retries")b->client.retries=p.second.GetValue<int64_t>();else if(k=="timeout")b->client.timeout_seconds=p.second.GetValue<int64_t>();else if(k=="secret")secret=p.second.ToString();}StringUtil::Trim(b->filter);if(b->filter.empty()||b->page_size<1||b->page_size>100000||b->max<0||b->client.timeout_seconds<1||b->client.retries>100)throw InvalidInputException("read_gcloud_metrics: filter and limits must be valid");auto cred=GetGcloudCredentials(c,secret);b->project=b->project.empty()?cred.project:b->project;if(b->project.empty())b->project=TryDiscoverAdcProject();if(b->project.empty())throw BinderException("read_gcloud_metrics: project is required (parameter, secret, or ADC)");b->client.endpoint=GcloudMonitoringEndpoint(cred);b->client.insecure_tls=cred.insecure_tls;b->client.auth.token=cred.token;b->client.auth.credentials_file=cred.credentials_file;b->client.auth.scope=kMonitoringReadScope;b->client.auth.quota_project=cred.quota_project;b->client.auth.insecure_tls=cred.insecure_tls;b->client.auth.timeout_seconds=b->client.timeout_seconds;n={"time_unix_nano","start_time_unix_nano","name","description","unit","int_value","double_value","service_name","service_namespace","service_instance_id","resource_attributes","scope_name","scope_version","scope_attributes","metric_attributes","flags","exemplars_json"};t={LogicalType::TIMESTAMP_NS,LogicalType::TIMESTAMP_NS,LogicalType::VARCHAR,LogicalType::VARCHAR,LogicalType::VARCHAR,LogicalType::BIGINT,LogicalType::DOUBLE,LogicalType::VARCHAR,LogicalType::VARCHAR,LogicalType::VARCHAR,LogicalType::VARCHAR,LogicalType::VARCHAR,LogicalType::VARCHAR,LogicalType::VARCHAR,LogicalType::VARCHAR,LogicalType::INTEGER,LogicalType::VARCHAR};return b;}
static unique_ptr<GlobalTableFunctionState>I(ClientContext&,TableFunctionInitInput&i){auto s=make_uniq<State>();auto&b=i.bind_data->Cast<Bind>();s->cols=i.column_ids;s->start=ResolveTimeSpec("start_time",b.start);s->end=ResolveTimeSpec("end_time",b.end);int64_t a,z;if(!ParseRfc3339ToNanos(s->start.c_str(),a)||!ParseRfc3339ToNanos(s->end.c_str(),z)||a>=z)throw InvalidInputException("read_gcloud_metrics: start_time must be before end_time");return s;}static void Scan(ClientContext&c,TableFunctionInput&i,DataChunk&o){auto&b=i.bind_data->Cast<Bind>();auto&s=i.global_state->Cast<State>();while(s.points.empty()&&!s.done)Fetch(c,b,s);idx_t n=0;while(n<STANDARD_VECTOR_SIZE&&!s.points.empty()&&(b.max==0||s.emitted<idx_t(b.max))){Map(b,s,s.points.front(),o,n++);s.points.pop_front();s.emitted++;}if(b.max>0&&s.emitted>=idx_t(b.max)){s.points.clear();s.done=true;}o.SetCardinality(n);}
}void RegisterGcloudMetricsFunction(ExtensionLoader&l){TableFunction f("read_gcloud_metrics",{},Scan,B,I);for(auto k:{"project","filter","start_time","end_time","alignment_period","per_series_aligner","cross_series_reducer","secret"})f.named_parameters[k]=LogicalType::VARCHAR;f.named_parameters["group_by_fields"]=LogicalType::LIST(LogicalType::VARCHAR);for(auto k:{"page_size","max_rows","retries","timeout"})f.named_parameters[k]=LogicalType::BIGINT;f.projection_pushdown=true;l.RegisterFunction(f);}}
